server:
  port: 8085

spring:
  cloud.stream:
    bindings:
      priceAndProfitConsumer-in-0:
        destination: priceAndProficChanged
        content-type: application/json
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost:9094