server:
  port: 8086

spring:
  cloud.stream:
    bindings:
      priceAndProfit-out:
        destination: priceAndProficChanged
        content-type: application/json
      kafka:
        binder:
          zkNodes: 127.0.0.1
          brokers: localhost:9092

third-party:
  host: https://api.coinbase.com/v2
